googlelogin.settings:
  type: config_object
  label: 'Social Login Google settings'
  mapping:
    client_id:
      type: text
      label: 'Client ID'
    client_secret:
      type: text
      label: 'Client Secret'
